console.log("Ilya");
console.log(2);
console.log("Добро" + " " + "пожаловать" + " " + "на курс");
// alert(2019);
console.log(2019 - 200);

document.getElementById("six").innerHTML = "Hello World";
// divSix. = "Hello World";
divSeven = document.getElementById("seven");
divSeven.innerHTML = 12 * 12;
divEight = document.querySelector("div.out-8");
divEight.innerHTML = "task-8";
divTen = document.querySelector("div.out-10");
divTen.innerHTML = "<h2>Hi</h2>";
divEleven = document.querySelector("div.out-11");
divEleven.innerHTML = "123";
divEleven.innerHTML += "456";
a = document.querySelector("div.out-12");
a.innerHTML = 3.1415;
out13 = document.querySelector("div.out-13");
out13.innerHTML =
  '<img src="https://static.wikia.nocookie.net/rustarwars/images/d/d6/Yoda_SWSB.png/revision/latest?cb=20171222112613" alt="js">';
z1 = 6;
z2 = 3;
document.querySelector("div.out-14").innerHTML = z1 * z2;
y1 = 6;
y2 = 3;
document.querySelector("div.out-15").innerHTML = y1 / y2;
x1 = "Hello";
x2 = 5;
document.querySelector("div.out-15").innerHTML = x1 + x2;
out17 = document.querySelector("div.out-17");
console.log(out17);
out18 = document.querySelector("div.out-18");
console.log(out18);
out18 = 5;
console.log(out18);
out19 = document.querySelector("div.out-19-test");
out18 = out19;
console.log(out19);
out20 = document.querySelector("div.out-20");
out20.textContent = "<h2>Hi</h2>";
